import Header from "@/components/header";
import "./globals.css";
import { Inter } from 'next/font/google'
import Footer from "@/components/footer";
import ToastProvider from "@/context/ToastProvider"
// Slider imports 
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Suspense } from "react";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Codcupon",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "https://codcupon.nyc3.digitaloceanspaces.com/f98c281be600e40254e4b5755891c682.webp" || "../../public/og-image.webp",
        width: 1200,
        height: 630
      },
    ],
  },
};

export default async function RootLayout({
  children,
  params
}) {
  
  return (
    <html lang="ro">
      <body
        className={`${inter.className} antialiased`}
      >
        <Suspense fallback={''}>
            <ToastProvider>
              <Header/>
                {children}
              <Footer/>
            </ToastProvider>
        </Suspense>
      </body>
    </html>
  );
}
